# --- Fonts ---
font_family      Ioskeley Mono Nerd Font Medium
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# --- Performance & Sync ---
repaint_delay    8
input_delay      2
sync_to_monitor  no

# --- Window Decoration ---
hide_window_decorations yes
window_padding_width    5
window_margin_width     0
confirm_os_window_close 0
background_opacity         0.60
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
shell_integration no-title

cursor_trail 0
url_style curly

# --- Cursor & Shell ---
cursor_shape     block
shell            zsh

# --- Interaction ---
allow_remote_control     yes
enable_wayland_clipboard true
map ctrl+c               copy_or_interrupt
map ctrl+v               paste_from_clipboard
scrollback_lines         10000
enable_audio_bell no

# --- Tab Bar ---
tab_bar_style           fade
tab_fade                1
active_tab_font_style   bold
inactive_tab_font_style normal

# BEGIN_KITTY_THEME
# Kanagawa_dragon
include current-theme.conf
# END_KITTY_THEME
