# colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
# base indexes to 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set-window-option -g automatic-rename on

# source config file
bind r source-file ~/.config/tmux/tmux.conf

# prefix key rebind
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# misc
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
set -s escape-time 0
set -g history-limit 2000

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# tmux sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
# Fuzzy switch between existing sessions
bind-key g display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
# Prompt for a name and create a new session
bind C-n command-prompt -p "New Session Name:" "new-session -s '%%'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'Nybkox/tmux-ukiyo'
set -g @ukiyo-theme "kanagawa/dragon"
set -g @ukiyo-ignore-window-colors true

set -g @ukiyo-plugins "cwd ram-usage git"
set -g @ukiyo-show-powerline false
set -g @ukiyo-clients-minimum 1
set -g @ukiyo-cwd-max-dirs "0"
set -g @ukiyo-cwd-max-chars "0"
set -g @ukiyo-color-bg-bar "#181616"

# Initialize TPM (Keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
