animations {
    enabled = true

    bezier = softSnap, 0.4, 0, 0.2, 1
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1
    bezier = slideEase, 0.12, 0, 0.39, 0
    bezier = slideWorkspace, 0.4, 0, 0.25, 1
    bezier = slidevert, 0.4, 0, 0.25, 1

    animation = global, 1, 10, default
    animation = border, 1, 2.39, easeOutQuint
    animation = windows, 1, 2.79, easeOutQuint
    animation = windowsIn, 1, 2, easeOutQuint, popin 70%
    animation = windowsOut, 1, 2, linear, popin 70%
    animation = windowsMove, 1, 1, softSnap
    animation = fadeIn, 1, 1, almostLinear
    animation = fadeOut, 1, 1, almostLinear
    animation = fade, 1, 1.03, quick
    animation = layers, 1, 2, easeOutQuint
    animation = layersIn, 1, 2, easeOutQuint, slide 10%
    animation = layersOut, 1, 4, softSnap, slide right

    animation = workspaces, 1, 0.5, slideWorkspace, slidevert
    animation = workspacesIn, 1, 0.5, slideWorkspace, slidevert
    animation = workspacesOut, 1, 0.5, slideWorkspace, slidevert
}
