decoration {
    rounding = 0
    shadow {
        enabled = false
    }
    blur {
        enabled = true
        size = 10 
        passes = 3
        ignore_opacity = true

        brightness = 0.6
        contrast = 1.5
        noise = 0.01
        vibrancy = 0.2

        new_optimizations = true
    }
}
