general {
    gaps_in = 0
    gaps_out = 0 
    border_size = 1
    col.active_border = rgb(504945)
    col.inactive_border = rgb(2c2826)
    resize_on_border = false
    no_focus_fallback = true
    allow_tearing = false
    layout = scrolling
}

scrolling {
    fullscreen_on_one_column = false
    column_width = 0.75
    direction = right
    follow_focus = true
    follow_min_visible = 0.6
    explicit_column_widths = 0.5,0.75,1.0
}

binds {
    scroll_event_delay = 0
    hide_special_on_workspace_change = true
}
