windowrule {
    name = "walker"
    match:class = dev.benz.walker
    float = true
    pin = true
    allows_input = on
    stay_focused = true
}

windowrule {
    name = "floating-rules"
    match:float = true
    suppress_event = fullscreen, maximize, activate, activatefocus
}
